version: '2'

services:
  timescaledb:
    build:
      context: ./database
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=stocksdb
    ports:
      - "5433:5432"
    volumes:
      - ./database:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  python-db-helper:
    build:
      context: ./python-db-helper
    depends_on:
      timescaledb:
        condition: service_healthy
    environment:
      - DB_HOST=timescaledb
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASS=password
      - DB_NAME=stocksdb
    volumes:
      - ./python-db-helper:/app
    command: ["python", "populate_stocks.py"]

  fastapi:
     build:
       context: ./timescale-fastapi
     depends_on:
       timescaledb:
         condition: service_healthy
     environment:
       - DB_HOST=timescaledb
       - DB_PORT=5432
       - DB_USER=postgres
       - DB_PASS=password
       - DB_NAME=stocksdb
     ports:
       - "8000:8000"
     volumes:
       - ./timescale-fastapi:/usr/app
     command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
  
  redis:
    image: redis:alpine
    ports:
      - 6379:6379
